id: P005409
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23565
  title: གསུང་འབུམ། དཀར་བརྒྱུད་བསྟན་འཛིན་ནོར་བུ
  author: ''
  volumes:
    7fd1bfceca5c451a818361faecfe0999:
      image_group_id: I2158
      title: ''
      volume_number: 1
      total_pages: 418
      base_file: v001.txt
