id: P005409
initial_creation_type: ocr
source_metadata:
  id: bdr:W23565
  title: གསུང་འབུམ། དཀར་བརྒྱུད་བསྟན་འཛིན་ནོར་བུ
  author: ''
  volumes:
    7fd1bfceca5c451a818361faecfe0999:
      image_group_id: I2158
      title: ''
      volume_number: 1
      total_pages: 418
