id: IABA6D7AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:15:49+00:00'
last_modified: '2022-06-08T02:52:46.608314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23565
  title: གསུང་འབུམ། དཀར་བརྒྱུད་བསྟན་འཛིན་ནོར་བུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ABA5:
      image_group_id: I2158
      title: ''
      total_pages: 418
      order: 1
      base_file: ABA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
