id: IABA6D7AB
legacy_id: P005409
ocr_import_info:
  bdrc_scan_id: W23565
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T02:13:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:16:37.504070+00:00'
last_modified: 2022-09-02 09:16:51.001008
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23565
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23565
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དཀར་བརྒྱུད་བསྟན་འཛིན་ནོར་བུ།
  author: བྲག་དཀར་བ་དཀར་བརྒྱུད་བསྟན་འཛིན་ནོར་བུ།
statistics:
  ocr_word_mean_confidence_index: 0.8444076232596408
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I2158:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2158
      total_pages: 418
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2158.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8444076232596408
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
